community.html, index.html, summit.html
Adding a Summit page to the Eiffel community website.
Added information about Eiffel Summit 2019.2 at Axis Communications AB.
=> Add an Eiffel summit page for the Eiffel community website

community.html, index.html
Update links of Code of Conduct (since they are migrating to .github repo)
Update eiffel-community links
(c) The contribution was provided directly to me by some other …
=> Update links in header and footer

summit.html
#12 
information about when and how online summit will happen
=> Eiffel online summit page

community.html, index.html, security.html, summit.html
Fixes #14 
Adds a page (security.html) with a list of known security vulnerabilities and the fixes to mitigate them
-
Security considerations today are important and this will show that we, the Eiffel-community, take it seriously.
The list may get long and hard to overview
by me, under the same open …
=> Add a security vulnerability report page

mission-and-vision.html, security.html, summit.html
#16 
There was a mistake in the previous PR adding Mission and Vision (#17). The header links became inconsistent between pages.
If we add any more pages we should split the header into a separate file rather than copy-pasting it, but... 
Header stays consistent when browsing the website.
by me, under …
=> Fixed problem with inconsistent header links.

archive/summit-2020-1.html, summit.html
--
Add info about the upcoming Eiffel summit 2021.1
--
information spreading
none
(c) The contribution was provided directly to me by some other
person who certified (a), …
=> Add info about summit 2021.1

summit.html
N/A
@sselberg has agreed to moderate a couple of the sessions. Updating the agenda accordingly.
None.
Agenda reflecting reality.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or
(c) The …
=> Summit: Make Sven Selberg moderator of two sessions

summit.html
N/A
Added link to slack for the summit.
None
A visible place for questions
None
(c) The contribution was provided directly to me by some other
person who certified (a), …
=> Add slack #summit channel link

summit.html
N/A; trivial
All slide decks added in https://github.com/eiffel-community/community/pull/110 and https://github.com/eiffel-community/community/pull/111 are getting links from https://eiffel-community.github.io/summit.html. Also adding links to all YouTube videos except one. **Do not merge until https://github.com/eiffel-community/community/pull/111 has been merged.**
Considered adding the slide link as a new table cell (alongside the difficulty level) but decided that it would be unnecessarily prominent and wouldn't fit well with the _What's cooking_ session where there were three speakers.
Makes it easier to locate presentation slides and videos.
None.
(a) The contribution was created in whole …
=> Summit: Add links to slide decks and videos

index.html
N/A; decision at the [2022-03-24 TC meeting](https://github.com/eiffel-community/community/blob/master/meetings/MEETINGS_TC_2022.md#March-24-2022).
Link to the Python Podcast.\_\_init__ episode that covered Eiffel from the index.html page. We already had a section that just contained a link to the Youtube channel so we generalize that section to cover all media. See the change in action at https://magnusbaeck.github.io/eiffel-community.github.io/.
None.
Provide additional material to users.
None.
(b) The contribution is based upon previous …
=> index.html: Link to Python Podcast.__init__ episode

summit.html
N/A
Reordered the agenda slightly in the end, and added some coffee breaks.
Also added names on all agenda items.
-
-
-
(c) The contribution was provided directly to me …
=> Add speakers & moderators to topics & adjust agenda

summit-2019-2.html, summit-2020-1.html, summit-2021-1.html
#37 
The archived summit pages in the archive directory have never rendered properly since they contained relative URLs to e.g. js/csi.min.js. Let's just move the archived files back to the root of the repo. We won't have that many summits that the number of files will be overwhelming.
PR in action:
- https://magnusbaeck.github.io/eiffel-community.github.io/summit-2019-2.html
- https://magnusbaeck.github.io/eiffel-community.github.io/summit-2020-1.html
- https://magnusbaeck.github.io/eiffel-community.github.io/summit-2021-1.html
Changing the relative URLs to match the directory layout (e.g. ../js/csi.min.js) works for the most part, but the relative URLs inside the included HTML files still won't work since they're evaluated against the including page's URL and not the included file's …
=> Move archive/* to the root to fix 404 errors

summit.html
N/A
As discussed in summit planning meetings, the last sign-up date of May 12 was unnecessarily early and might dissuade people. Change the date to June 5 instead, i.e. a week before the summit.
None.
Possibly more people signing up.
Less time to cater to people's preferences or change the rooms to accommodate more people.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with …
=> summit.html: Postpone last sign-up date to June 5

summit.html
Fixes #50 
Add a agenda for the summit 2023
Preview: https://e-backmark-ericsson.github.io/eiffel-community.github.io/summit.html
None
Clarity
None
(c) The contribution …
=> Add summit 2023 agenda

summit.html
-
Update summit page since the summit is now sold out
Preview: https://e-backmark-ericsson.github.io/eiffel-community.github.io/summit.html
-
Clear message
-
(c) The …
=> Add sold out and minor updates

summit.html
Closes #54 
Fix the date of Eiffel Summit 2023.1 second day
N/A
To give community the correct information.
None
(c) The contribution was provided directly to me by some …
=> Fix date of Eiffel Summit 2023.1 second day

summit.html
None
Update Summit agenda after planning meeting on June 8.
Preview: https://e-backmark-ericsson.github.io/eiffel-community.github.io/summit.html
-
-
-
(c) The …
=> Update summit agenda

summit.html
N/A
Switch DORA session and Conformance session in agenda. Add information about Tuesday and Wednesday locations. Add link to parking map.
-
-
-
(c) The contribution was …
=> Move DORA session. Add location and parking info.

summit.html
N/A
After a first meeting to set the summit agenda it's in sufficiently good shape to include in the summit page. See it live at https://magnusbaeck.github.io/eiffel-community.github.io/summit.html.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to …
=> Add preliminary summit agenda

summit.html
N/A; this is a trivial change
Postpone the last registration date for the summit by a week. The Volvo folks said this was early enough for their logistics.
N/A
N/A
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated …
=> Summit: Change last registration date to Aug 22

summit.html
N/A
After a discussion to update the summit agenda, we decide to 
- Adjust the lunch time
- Change some topics
- Add reserved place for topics come before/during the summit
See it live at https://jiapengsun.github.io/eiffel-community.github.io/summit.html
by me, under the same open source license …
=> Summit : agenda update for summit 2024

summit.html
After a discussion to update the summit agenda, we decide to
Add and merge some topics
See it live at https://jiapengsun.github.io/eiffel-community.github.io/summit.html …
=> summit agenda update based on meeting 240819

summit.html
After a discussion to update the summit agenda, we decide to
Reorder the topics on day 2 and reduce QA to 30min for finishing earlier
See it live at https://jiapengsun.github.io/eiffel-community.github.io/summit.html
permitted to submit under a …
=> agenda update 240821

summit.html
N/A
- Add at least one name to each session.
- Add company for each name.
- Short submodules session and add Eiffel Collector session.
N/A
N/A
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or
(c) …
=> Summit: Add names to sessions and add session for Eiffel Collector

summit.html
N/A
Add a link to the final video from the 2024 summit to the summit page. See the result at https://magnusbaeck.github.io/eiffel-community.github.io/summit.html.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as …
=> summit.html: Add remaining YouTube link

summit.html
N/A
Removing the preliminary wording for the agenda and adjusting a few descriptions and names.
None.
None.
(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or
(c) The contribution was provided …
=> summit.html: Furher refinements
